# Generated by Django 4.2.7 on 2026-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name_en', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('rain_probability', 'Rain Probability'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('wind_speed', 'Wind Speed'), ('cloud_cover', 'Cloud Cover')], max_length=50)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('advice_en', models.TextField()),
                ('advice_hi', models.TextField()),
                ('advice_mr', models.TextField()),
                ('priority', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['crop_name_en', 'priority'],
            },
        ),
    ]
