# Generated by Django 4.2.7 on 2026-09-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_hi', models.CharField(max_length=100)),
                ('name_mr', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='🌱', max_length=10)),
                ('description_en', models.TextField(blank=True)),
                ('description_hi', models.TextField(blank=True)),
                ('description_mr', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid'), ('annual', 'Annual')], max_length=20)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(default='Maharashtra', max_length=200)),
                ('priority', models.IntegerField(default=5)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='crops.crop')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
