# Generated by Django 4.2.7 on 2026-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200, unique=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('last_location_name', models.CharField(blank=True, max_length=200)),
                ('last_lat', models.FloatField(blank=True, null=True)),
                ('last_lon', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
